artifacts_root: artifacts



data_ingestion:
  source_URL: "https://github.com/nishajaiswal03/Text-Summarizer-Project/raw/refs/heads/main/samsum_dataset.zip"
  root_dir: "artifacts/data_ingestion"
  local_data_file: "artifacts/data_ingestion/data.zip"
  unzip_dir: "artifacts/data_ingestion"



data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["samsum_train.json", "samsum_test.json", "samsum_validation.json"]